version: '3.0'

services:
  gotoServer:
    container_name: gotoServer
    image: 'node'
    environment:
      - GOTO_PORT=8080
      - GOTO_MONGOURL=mongodb://MongoDB:27017/goto
      - GOTO_GOTO_JWT_SECRET="here is a secret"
      - GOTO_GOTO_JWT_EXPIRATION=1h
    ports:
      - '80:8080'
      - '9229:9229'
    volumes:
      - '.:/server'
    command: "sh -c 'node  --inspect=0.0.0.0:9229 -r
      /server/node_modules/ts-node/register /server/src/index.ts'"

  mongo:
    container_name: MongoDB
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'
    command: "sh -c 'mongod --dbpath /data/db --bind_ip_all'"
